### ISSUE TITLE
[task] infinity-carousel

### ISSUE THREAD

**Issue by ilyassab** [Atlantis-Lab/uikit#113]
Дать возможность carousel быть цикличной. Идея: вычислять позицию текущего слайд-итема, если слайд-итем-идекс + степ > конечный индекс слайдера, то переносить первые слайды в конец.

**Comment by TorinAsakura** [comment]
Предлагаю написать вотчер для этого дела, чтобы он отслеживал состояния и пропсы тебе передавал, для вычисления потребуется слишком много писанины делать

**Comment by TorinAsakura** [comment]
@ilyassab status
