### ISSUE TITLE
[feature] add stories for slideshow

### ISSUE THREAD

**Issue by GlebAO** [Atlantis-Lab/uikit#141]
### С чем связан запрос на фичу?

Необходимо протестировать работоспособность плагина Slideshow

### Расскажите как вы это себе видите
- склонировать репозиторий  Atlantis-Lab/uikit 
- установить storybook и настроить, чтобы сторисы брались из директорий с плагинами uikit
- Создать папку stories в директории с плагином
- Создать файл slideshow.stories.tsx

### Приложите примеры реализаций

https://github.com/Atlantis-Lab/serenity/blob/dev/frontend/ui/button/src/stories/Button.story.tsx

**Comment by GlebAO** [comment]
@TorinAsakura  Склонировал репозиторий. Установил пакеты с помощью команды yarn. В node_modules пакеты есть. Не могу понять почему при импорте не видит пакетов. К примеру в Slideshow.tsx 
`import { contentWidth }  from '@atlantis-lab/utils'` , @atlantis-lab/utils - не находит

**Comment by TorinAsakura** [comment]
> @TorinAsakura Склонировал репозиторий. Установил пакеты с помощью команды yarn. В node_modules пакеты есть. Не могу понять почему при импорте не видит пакетов. К примеру в Slideshow.tsx
> `import { contentWidth } from '@atlantis-lab/utils'` , @atlantis-lab/utils - не находит
> При том `import styled from '@emotion/styled'` импортируется нормально

Очень хорошо. Какие дальнейшие действия?

**Comment by GlebAO** [comment]
> 
> 
> > @TorinAsakura Склонировал репозиторий. Установил пакеты с помощью команды yarn. В node_modules пакеты есть. Не могу понять почему при импорте не видит пакетов. К примеру в Slideshow.tsx
> > `import { contentWidth } from '@atlantis-lab/utils'` , @atlantis-lab/utils - не находит
> > При том `import styled from '@emotion/styled'` импортируется нормально
> 
> Очень хорошо. Какие дальнейшие действия?

Попробовал всё пересобрать, но не помогло.
