### ISSUE TITLE
[feature] add story for input

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/uikit#158]
### С чем связан запрос на фичу?

Необходимо протестировать работоспособность плагина Input

### Расскажите как вы это себе видите

- Создать папку `stories` в `src` в директории с плагином
- Создать файл `Input.story.tsx` со сторисом

### Приложите примеры реализаций

https://github.com/Atlantis-Lab/uikit/tree/master/packages/carousel

**Comment by TorinAsakura** [comment]
@TFK70 папки должны называться story, я уже писал об этом, исправь и переименуй их
