### ISSUE TITLE
[bug] fix slideshow's margins

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/uikit#167]
### Описание бага

**@atlantis-lab/slideshow@0.7.2**
Слайдшоу некорректно взаимодействует с окружающими элементами и потоком

### Воспроизведение

Шаги для воспроизведения бага:

1. Идем в **packages/storybook/** и поднимаем storybook командой `yarn storybook`
2. Идем в **packages/slideshow/src/stories/Slideshow.story.tsx**
3. Теперь зададим небольшой layout для удобства, например такой:
```javascript
import { Column, Row } from '@atlantis-lab/layout'

export const ExampleSlideshow = ({ time, transition = '.5s', controlsType }) => (
    <Column>
        <Row>
            <Slideshow time={time} transition={transition} controlsType={controlsType}>
                <h1>Child 1</h1>
                <h1>Child 2</h1>
                <h1>Child 3</h1>
            </Slideshow>
        </Row>
    </Column>
)
```
3. Добавим в окружение к слайдшоу элемент, этого будет достаточно:
```javascript
export const ExampleSlideshow = ({ time, transition = '.5s', controlsType }) => (
    <Column>
        <Row>
            <Slideshow time={time} transition={transition} controlsType={controlsType}>
                <h1>Child 1</h1>
                <h1>Child 2</h1>
                <h1>Child 3</h1>
            </Slideshow>
        </Row>
        <Row>
            <h1>{'An element'}</h1>
        </Row>
    </Column>
)
```
4. И не добавляйте `<Layout flexBasis={...}/>` или что-то в этом духе, что могло бы "искусственно" задать отступ. Результат в материалах

### Ожидаемое поведение

Слайдшоу не должно игнорировать элементы вокруг (на скриншоте предполагаемое поведения без отступов "вручную"): 
![image](https://user-images.githubusercontent.com/62806448/106269597-8ac3f000-624e-11eb-801c-203a654d2e0e.png)

### Материалы

Элементы накладываются друг на друга т.к. слайдшоу идет вне потока

![image](https://user-images.githubusercontent.com/62806448/106269305-2a34b300-624e-11eb-8c25-b4ead21c1483.png)

### Предполагаемая причина

Данный кусок кода в **packages/slideshow/src/Slideshow.tsx**:
```javascript
const StyledSlide = styled.div<any>(({ opacity, transition, visibility }) => ({
  position: 'absolute',
  transition,
  opacity,
  visibility,
}))
```
А именно `position: absolute`, из-за которого элемент не берёт в учёт окружение

__Примечание__

"Путь наименьшего сопротивления" со своим ньюансом:

1. Убрать `position: absolute` 
2. Заменить свойства `visibility: hidden` и `visibility: visible` на `display: none` и `display: block` соответственно
Причина простая: `visibility: hidden` лишь делает элемент невидимым, в то время как `display: none` его удаляет. Это важно, т.к. после того, как мы уберём `position: absolute` и оставим `visibility`, слайды будут тоже учитывать друг друга и получится следующее: 
![image](https://user-images.githubusercontent.com/62806448/106270301-9663e680-624f-11eb-855f-3dea53fd0ecf.png)
![image](https://user-images.githubusercontent.com/62806448/106270334-a67bc600-624f-11eb-98bb-8d1c44fb2fad.png)
![image](https://user-images.githubusercontent.com/62806448/106270613-1427f200-6250-11eb-9291-1c740e16d892.png)

**Тот самый ньюанс**: 'display: none' исправляет эту проблему, но в таком случае ломается `transition`, так что задача: добиться вышеперечисленного с учётом `transition` свойства

### Данные окружения

- Ubuntu@20.04
- Chrome Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by TorinAsakura** [comment]
@TFK70 я уже писал об этом в задаче по слайдеру - нужно создать слушатель и управляющий потоком хок, иначе добиться нормального вайпап с анимацией не получится
