### ISSUE TITLE
[feature] add background component

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/uikit#200]
### С чем связан запрос на фичу?

- Добавить компонент управляющий задним фоном
- Так же написать для него story и тест

### Расскажите как вы это себе видите

```javascript
import styled  from '@emotion/styled'
import { Box } from '@atlantis-lab/layout'
import {
  backgroundImage,
  backgroundSize,
  system,
} from 'styled-system'

export const Background = styled(Box)<any>(({backgroundColor}) =>( {
  position: 'fixed',
  width: '100%',
  height: '100%',
  backgroundColor,
}),
  backgroundSize,
  backgroundImage,
  system({
    cursor: true,
  })
)

Background.defaultProps = {
  display: 'flex',
  backgroundPosition: 'center',
  backgroundRepeat: 'no-repeat',
  backgroundSize: 'cover',
}
```
### Примечания

- В styled-system есть не все нужные нам пропы, так что что-то (backgroundColor, например) придется имплементировать как в примере выше
- Пример инициализации компонента: 
```javascript
<Background backgroundColor='#000' />
```
После этого на странице появится бекграунд со стилями соответствующими пропсам

__На данный момент будет реализовано 3 основных свойства:__
- backgroundColor (цвет фона)
- backgroundImage (загрузка фонового изображения)
- backgroundSize`: auto | cover | contain` (применимо только к изображению, загруженному в качестве бекграунда)

**Comment by TorinAsakura** [comment]
@TFK70 что-то как-то маловато для бэкграунда…
вот набор, который использовался у нас в последний раз, что-то уместно, а что-то нет
```
borderRadius?: string
  width?: string | number | string[] | number[]
  minHeight?: string | number | string[] | number[]
  minWidth?: string | number | string[] | number[]
  height?: string | number | string[] | number[]
  backgroundColor?: string
  backgroundImage?: string | string[]
  backgroundSize?: string | string[]
  backgroundPosition?: string | string[]
  absolute?: boolean
  mediumBorder?: boolean
  hover?: boolean
  transition?: string
  cover?: boolean
  position?: string
  stub?: boolean
  cursor?: string
```
