### ISSUE TITLE
[feature] add test for theme package

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/uikit#234]
### С чем связан запрос на фичу?

Необходимо протестировать корректность работы пакета `theme`

### Расскажите как вы это себе видите

1. Протестировать работоспособность заданной системы типов для темы
2. Протестировать работоспособность и совместимость ThemeProvider с плагинами использующими latest API (например `@atlantis-lab/next-app-with-emotion`)

### Приложите примеры реализаций

https://github.com/Atlantis-Lab/uikit/tree/master/packages/background

**Comment by TFK70** [comment]
@TorinAsakura мне кажется, что учитывая наши требования от пакета будет разумнее экспортировать интерфейс, а не пустой объект с типом

### Сейчас

```javascript
export const borders: { [key: string]: string } = {}
```

### Будет

```javascript
export interface Borders {[key: string]: string}
```

**Comment by TorinAsakura** [comment]
@TFK70 Можно. Тут без разницы.
